[metadata]
creation_date = "2020/04/24"
ecs_version = ["1.5.0"]
maturity = "production"
updated_date = "2020/08/21"

[rule]
author = ["Elastic"]
description = """
Kernel modules and extensions are pieces of code that can be loaded and unloaded into the kernel upon demand. They
extend the functionality of the kernel without the need to reboot the system. This rule identifies attempts to remove a
kernel module or extension.
"""
false_positives = [
    """
    There is usually no reason to remove modules, but some buggy modules require it. These can be exempted by username.
    Note that some Linux distributions are not built to support the removal of modules at all.
    """,
]
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Kernel Module Removal"
note = "Auditbeat configurations: For macOS systems, Auditbeat must be run with an account that has access to the binaries in the /usr/sbin, /sbin, /usr/bin, and /bin directories. For Linux systems, to avoid conflicts with auditd, you will need to stop and disable auditd with 'sudo service stop auditd && sudo systemctl disable auditd'."references = ["http://man7.org/linux/man-pages/man8/modprobe.8.html"]
risk_score = 73
rule_id = "cd66a5af-e34b-4bb0-8931-57d0a043f2ef"
severity = "high"
tags = ["Elastic", "Linux", "macOS"]
type = "query"

query = '''
event.category:process and event.type:start and process.args:((rmmod and sudo) or kextunload or (modprobe and sudo and ("--remove" or "-r")))
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1089"
name = "Disabling Security Tools"
reference = "https://attack.mitre.org/techniques/T1089/"


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1215"
name = "Kernel Modules and Extensions"
reference = "https://attack.mitre.org/techniques/T1215/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
