[metadata]
creation_date = "2020/04/27"
ecs_version = ["1.5.0"]
maturity = "production"
updated_date = "2020/08/24"

[rule]
author = ["Elastic"]
description = """
Adversaries may attempt to disable the Syslog service in an attempt to an attempt to disrupt event logging and evade
detection by security controls.
"""
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Attempt to Disable Syslog Service"
note = "Auditbeat configurations: For macOS systems, Auditbeat must be run with an account that has access to the binaries in the /usr/sbin, /sbin, /usr/bin, and /bin directories. For Linux systems, to avoid conflicts with auditd, you will need to stop and disable auditd with 'sudo service stop auditd && sudo systemctl disable auditd'."
risk_score = 47
rule_id = "2f8a1226-5720-437d-9c20-e0029deb6194"
severity = "medium"
tags = ["Elastic", "Linux", "macOS"]
type = "query"

query = '''
event.category:process and event.type:start and
(process.args:(launchctl and unload and /System/Library/LaunchDaemons/com.apple.syslogd.plist))
or (((process.name:service and process.args:stop) or (process.name:chkconfig and process.args:off)
or (process.name:systemctl and process.args:(disable or stop or kill))) and process.args:(syslog or
rsyslog or "syslog-ng"))
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1089"
name = "Disabling Security Tools"
reference = "https://attack.mitre.org/techniques/T1089/"


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
