[metadata]
creation_date = "2020/04/23"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/11/16"

[rule]
author = ["Elastic"]
description = """
Loadable Kernel Modules (or LKMs) and Kernel Extensions are pieces of code that can be loaded and unloaded into the
kernel upon demand. They extend the functionality of the kernel without the need to reboot the system. This identifies
attempts to enumerate information about a kernel module or extension.
"""
false_positives = [
    """
    Security tools and device drivers may run these programs in order to enumerate kernel modules or extensions. Use of
    these programs by ordinary users is uncommon. These can be exempted by process name or username.
    """,
]
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Enumeration of Kernel Modules or Extensions"
note = "Auditbeat configurations: For macOS systems, Auditbeat must be run with an account that has access to the binaries in the /usr/sbin, /sbin, /usr/bin, and /bin directories. For Linux systems, to avoid conflicts with auditd, you will need to stop and disable auditd with 'sudo service stop auditd && sudo systemctl disable auditd'."
risk_score = 47
rule_id = "2d8043ed-5bda-4caf-801c-c1feb7410504"
severity = "medium"
tags = ["Elastic", "Linux", "macOS", "Threat Detection", "Discovery"]
type = "query"

query = '''
event.category:process and event.type:start and process.args:(((kmod and list) or (kmod and static-nodes)) or (depmod or lsmod or modinfo or kextstat))
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1082"
name = "System Information Discovery"
reference = "https://attack.mitre.org/techniques/T1082/"


[rule.threat.tactic]
id = "TA0007"
name = "Discovery"
reference = "https://attack.mitre.org/tactics/TA0007/"
