[metadata]
creation_date = "2020/02/18"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/11/16"

[rule]
author = ["Elastic"]
description = """
The Linux mknod program is sometimes used in the command payload of a remote command injection (RCI) and other exploits.
It is used to export a command shell when the traditional version of netcat is not available to the payload.
"""
false_positives = [
    """
    Mknod is a Linux system program. Some normal use of this program, at varying levels of frequency, may originate from
    scripts, automation tools, and frameworks. Usage by web servers is more likely to be suspicious.
    """,
]
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Mknod Process Activity"
references = ["https://pen-testing.sans.org/blog/2013/05/06/netcat-without-e-no-problem"]
risk_score = 21
rule_id = "61c31c14-507f-4627-8c31-072556b89a9c"
severity = "low"
tags = ["Elastic", "Linux", "macOS", "Persistence"]
type = "query"

query = '''
event.category:process and event.type:start and process.name:mknod
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1133"
name = "External Remote Services"
reference = "https://attack.mitre.org/techniques/T1133/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
