[metadata]
creation_date = "2020/02/18"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/11/16"

[rule]
author = ["Elastic"]
description = "Identifies processes running in a temporary folder. This is sometimes done by adversaries to hide malware."
false_positives = [
    """
    Build systems, like Jenkins, may start processes in the `/tmp` directory. These can be exempted by name or by
    username.
    """,
]
index = ["auditbeat-*"]
language = "kuery"
license = "Elastic License"
name = "Unusual Process Execution - Temp"
note = "Auditbeat configurations: For macOS systems, Auditbeat must be run with an account that has access to the binaries in the /usr/sbin, /sbin, /usr/bin, and /bin directories. For Linux systems, to avoid conflicts with auditd, you will need to stop and disable auditd with 'sudo service stop auditd && sudo systemctl disable auditd'."
risk_score = 47
rule_id = "df959768-b0c9-4d45-988c-5606a2be8e5a"
severity = "medium"
tags = ["Elastic", "Linux", "macOS", "Persistence"]
type = "query"

query = '''
event.category:process and event.type:start and
(process.working_directory:/tmp or process.executable:(/private/tmp* or /private/var/tmp*))
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1574"
name = "Hijack Flow Control"
reference = "https://attack.mitre.org/techniques/T1574/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"
