[metadata]
creation_date = "2020/02/18"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/11/16"

[rule]
author = ["Elastic"]
description = """
Strace runs in a privileged context and can be used to escape restrictive environments by instantiating a shell in order
to elevate privileges or move laterally.
"""
false_positives = [
    """
    Strace is a dual-use tool that can be used for benign or malicious activity. Some normal use of this command may
    originate from developers or SREs engaged in debugging or system call tracing.
    """,
]
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Strace Process Activity"
references = ["https://en.wikipedia.org/wiki/Strace"]
risk_score = 21
rule_id = "d6450d4e-81c6-46a3-bd94-079886318ed5"
severity = "low"
tags = ["Elastic", "Linux", "macOS"]
type = "query"

query = '''
event.category:process and event.type:start and process.name:(strace or dtrace)
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1548"
name = "Abuse Elevation Control Mechanism"
reference = "https://attack.mitre.org/techniques/T1548/"


[rule.threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"
