[metadata]
creation_date = "2020/04/13"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/11/16"

[rule]
author = ["Elastic"]
description = """
A sudoers file specifies the commands that users or groups can run and from which terminals. Adversaries can take
advantage of these configurations to execute commands as other users or spawn processes with higher privileges.
"""
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Sudoers File Accessed"
note = "Auditbeat configurations: For macOS systems, Auditbeat must be run with an account that has access to the binaries in the /usr/sbin, /sbin, /usr/bin, and /bin directories. For Linux systems, to avoid conflicts with auditd, you will need to stop and disable auditd with 'sudo service stop auditd && sudo systemctl disable auditd'."
risk_score = 21
rule_id = "931e25a5-0f5e-4ae0-ba0d-9e94eff7e3a4"
severity = "low"
tags = ["Elastic", "Linux", "macOS", "Privilege Escalation"]
type = "query"

query = '''
event.category:(file or process) and event.type:(start or change) and
(file.path:(/etc/.sudoers.tmp.swp or /etc/sudoers.tmp) or process.args:visudo)
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1169"
name = "Sudo"
reference = "https://attack.mitre.org/techniques/T1169/"


[rule.threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"
