[metadata]
creation_date = "2020/09/04"
ecs_version = ["1.6.0"]
maturity = "development"
updated_date = "2020/09/04"

[rule]
anomaly_threshold = 50
author = ["Elastic"]
description = "description"
false_positives = ["Uncommon user command activity can be due to an engineer logging onto a server instance in order to perform manual
  troubleshooting or reconfiguration."]
license = "Elastic License"
machine_learning_job_id = "test"
name = "name"
note = "note"
risk_score = 21
rule_id = "fee18557-e035-4464-b517-e91084ae6969"
severity = "low"
tags = ["Elastic", "Linux", "ML"]
type = "machine_learning"
