[metadata]
creation_date = "2020/11/24"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/11/24"

[rule]
author = ["Elastic"]
description = """
Identifies the creation of Local Security Authority Process (lsass.exe) memory dump. This may indicate credential access
attempt via utilities such as TaskMgr.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Lsass Memory Dump Created"
risk_score = 73
rule_id = "f2f46686-6f3c-4724-bd7d-24e31c70f98f"
severity = "high"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Credential Access"]
type = "query"

query = '''
event.category:file and file.name:lsass.DMP
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1003"
name = "OS Credential Dumping"
reference = "https://attack.mitre.org/techniques/T1003/"


[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

