[metadata]
creation_date = "2020/08/24"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/11/09"

[rule]
author = ["Elastic"]
description = """
A suspicious Endpoint Security parent process was detected. This may indicate a process hollowing or other form of code
injection.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
name = "Suspicious Endpoint Security Parent Process"
risk_score = 47
rule_id = "b41a13c6-ba45-4bab-a534-df53d0cfed6a"
severity = "medium"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Defense Evasion"]
timeline_id = "76e52245-7519-4251-91ab-262fb1a1728c"
type = "eql"

query = '''
process where event.type in ("start", "process_started", "info") and
 process.name in ("esensor.exe", "elastic-endpoint.exe", "elastic-agent.exe") and
 /* add FPs here */
  /* avoid null parent process executable */
  process.parent.executable != null and

  not wildcard(process.parent.executable,"C:\\Program Files\\Elastic\\*",
                                         "C:\\Windows\\System32\\services.exe",
                                         "C:\\Windows\\System32\\WerFault*.exe")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1036"
name = "Masquerading"
reference = "https://attack.mitre.org/techniques/T1036/"


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"
