[metadata]
creation_date = "2020/10/28"
ecs_version = ["1.6.0"]
maturity = "production"
updated_date = "2020/10/28"

[rule]
author = ["Elastic"]
description = """
Identifies creation or change of a DLL module within a Windows SxS local folder. Adversaries may abuse shared modules to
execute malicious payloads by instructing the Windows module loader to load DLLs from arbitrary local paths.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
name = "Execution via local SxS Shared Module"
note = "SxS DotLocal folder is a legit feature that can be abused to hijack standard modules loading order by forcing an executable on the same application.exe.local folder to load a malicious DLL module from the same directory. "
references = ["https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-redirection"]
risk_score = 43
rule_id = "a3ea12f3-0d4e-4667-8b44-4230c63f3c75"
severity = "medium"
tags = ["Elastic", "Windows"]
type = "eql"

query = '''
file where wildcard(file.path, "*\\*.exe.local\\*.dll")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1129"
name = "Shared Modules"
reference = "https://attack.mitre.org/techniques/T1129/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

