[metadata]
creation_date = "2020/11/11"
ecs_version = ["1.6.0"]
maturity = "development"
query_schema_validation = false
updated_date = "2020/11/11"

[rule]
author = ["Elastic"]
description = """
Identifies potential behavior of SharpRDP, which is a tool that can be used to perform authenticated command execution against a
remote target via Remote Desktop Protocol (RDP) for the purposes of lateral movement.
"""
from = "now-9m"
index = ["logs-endpoint.events.*", "winlogbeat-*"]
language = "eql"
license = "Elastic License"
name = "Potential SharpRDP Behavior"
references = [
    "https://posts.specterops.io/revisiting-remote-desktop-lateral-movement-8fb905cb46c3",
    "https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Lateral%20Movement/LM_sysmon_3_12_13_1_SharpRDP.evtx",
]
risk_score = 73
rule_id = "8c81e506-6e82-4884-9b9a-75d3d252f967"
severity = "high"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Lateral Movement"]
type = "eql"

query = '''
/* Incoming RDP followed by RunMRU new string value set to cmd, powershell, taskmgr or tsclient followed by process execution within 1m */

sequence by host.id with maxspan=1m
  [network where event.type == "start" and process.name == "svchost.exe" and destination.port == 3389 and 
   event.action == "connection_accepted" and network.direction == "incoming" and network.transport == "tcp" and
   not source.address in ("127.0.0.1", "::1")
  ]

  [registry where process.name == "explorer.exe" and 
   wildcard(registry.path, "HKEY_USERS\\*\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU\\*") and
   wildcard(registry.data.strings, "cmd.exe*", "powershell.exe*", "taskmgr*", "\\\\tsclient\\*.exe\\*")
  ]
  
  [process where event.type in ("start", "process_started") and process.name != "conhost.exe" and
   (process.parent.name in ("cmd.exe","powershell.exe","taskmgr.exe") or
   wildcard(process.args, "\\\\tsclient\\*.exe"))
   ]
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1021"
name = "Remote Services"
reference = "https://attack.mitre.org/techniques/T1021/"


[rule.threat.tactic]
id = "TA0008"
name = "Lateral Movement"
reference = "https://attack.mitre.org/tactics/TA0008/"
