[metadata]
creation_date = "2020/11/11"
ecs_version = ["1.6.0"]
maturity = "development"
query_schema_validation = false
updated_date = "2020/11/11"

[rule]
author = ["Elastic"]
description = """
Identifies behavior execution of SharRdp a tool that can be used to perform authenticated command execution against a
remote target via Remote Desktop Protocol for the purposes of lateral movement.
"""
from = "now-9m"
index = ["logs-endpoint.events.*", "winlogbeat-*"]
language = "eql"
license = "Elastic License"
name = "Potential SharpRdp Detected"
references = ["https://posts.specterops.io/revisiting-remote-desktop-lateral-movement-8fb905cb46c3"]
risk_score = 73
rule_id = "8c81e506-6e82-4884-9b9a-75d3d252f967"
severity = "high"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Lateral Movement"]
type = "eql"

query = '''
/* Incoming RDP followed by RunMRU new string value set to cmd, powershell, taskmgr or tsclient within 5m */
sequence with maxspan=5m
  [network where event.type == "start" and process.name == "svchost.exe" and
  destination.port == 3389 and event.action == "connection_accepted" and network.direction == "incoming" and
  network.transport == "tcp" and not source.address in ("127.0.0.1", "::1")
  ] by host.id
  [registry where process.name == "explorer.exe" and
   wildcard(registry.path, "HKEY_USERS\\*\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU\\*") and
   wildcard(registry.data.strings, "cmd.exe*", "powershell.exe*", "taskmgr*", "\\\\tsclient\\*.exe\\*")
  ] by host.id
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1021"
name = "Remote Services"
reference = "https://attack.mitre.org/techniques/T1021/"


[rule.threat.tactic]
id = "TA0008"
name = "Lateral Movement"
reference = "https://attack.mitre.org/tactics/TA0008/"

